services:
    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    sg_datatables.datatable.abstract:
        class: Sg\DatatablesBundle\Datatable\AbstractDatatable
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - '@sg_datatables.extension_registry'

    sg_datatables.extension_registry:
        class: Sg\DatatablesBundle\Datatable\Extensions
        public: false
        calls:
            - ['addExtension',['@sg_datatables.extension.button']]
            - ['addExtension',['@sg_datatables.extension.buttons']]
            - ['addExtension',['@sg_datatables.extension.fixed_header']]
            - ['addExtension',['@sg_datatables.extension.responsive']]
            - ['addExtension',['@sg_datatables.extension.row_group']]
            - ['addExtension',['@sg_datatables.extension.select']]

    sg_datatables.response: #DEPRECATED
        class: Sg\DatatablesBundle\Response\Doctrine\DatatableResponse
        parent: sg_datatables.response.doctrine

    sg_datatables.response.doctrine:
        class: Sg\DatatablesBundle\Response\Doctrine\DatatableResponse
        public: true
        arguments:
            - '@request_stack'

    sg_datatables.response.elastica:
        class: Sg\DatatablesBundle\Response\Elastica\DatatableResponse
        public: true
        arguments:
            - '@request_stack'

    sg_datatables.factory:
        class: Sg\DatatablesBundle\Datatable\DatatableFactory
        public: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@twig'

    sg_datatables.extension.fixed_header:
        class: Sg\DatatablesBundle\Datatable\Extension\FixedHeaderFooter

    sg_datatables.extension.select:
        class: Sg\DatatablesBundle\Datatable\Extension\Select

    sg_datatables.extension.button:
        class: Sg\DatatablesBundle\Datatable\Extension\Button

    sg_datatables.extension.buttons:
        class: Sg\DatatablesBundle\Datatable\Extension\Buttons

    sg_datatables.extension.responsive:
        class: Sg\DatatablesBundle\Datatable\Extension\Responsive

    sg_datatables.extension.row_group:
        class: Sg\DatatablesBundle\Datatable\Extension\RowGroup

